### ISSUE TITLE
[Blockly][Codegenerator] MCU-S2 Blockly Review

### ISSUE THREAD

**Issue by Thiemann96** [sensebox/React-Ardublockly#252]
### Task List for MCU-S2

- [x] Display working
- [x] MPU6050 (with Display)
- [x] Photodiode
  - Change value unit to something other than Illumincance in Lux => Light Intensity?
- [ ] RBG-LED (on Board)
  - Put the onBoard LED Block at the top one may get confused by the amount of different RGB's ==> make it more clear which one is on Board, (maybe have a category called "onBoard Components"?)
  - Is the WS2818 the same RGB that is onBoard? The initialize block and the set block should be named the same. One is "RGB LED (WS2818)" the other is "RGB-LED"
- [x] HDC 1080 (with Display)
- [ ] SD Card
  - Needs to be adjusted to [this example](https://github.com/sensebox/senseBox-MCU-S2-ESP32S2/blob/main/examples/sd-card/sd-card.ino). The code in blockly somehow breaks the MCU where you have to manually reset it
  - `addMeasurement' was not declared in this scope` When using "Save Measurement" Block
- [ ] WiFi
  - Getting error message when trying to use the WiFi Block
  - Whats the difference between WiFi and ESPNOW?
- [ ] WiFi AP
  - The name of AP is taken as a variable. Expected behaviour: Name is taken as a string, see picture
![image](https://github.com/sensebox/React-Ardublockly/assets/18304210/2cd1dd43-560c-4d5f-8e18-ae9f983e0a3b)

- [ ] Upload to OSeM (not yet tested, see WiFi)
- [x] Upload to TTN 
- [ ] Connect BLE (not yet tested)
- [x] RTC
  - Remove "internal" RTC as there seems to be none which can be accessed via Arduino yet

**Comment by Thiemann96** [comment]
[ ] Change the background image of the scratchpad(?) to the MCU-S2 (right now the MCU:mini is displayed)
